create extension if not exists "pgcrypto";

create table if not exists public.accounts (
  id text primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  password text not null,
  name text not null,
  rank text not null default '',
  tel text not null default '',
  email text not null default '',
  role text not null default 'user',
  del_yn text not null default 'N',
  updated_by text not null default ''
);

create table if not exists public.clients (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  name text not null,
  manager text not null default '',
  tel text not null default '',
  addr text not null default '',
  time text not null default '',
  lunch text not null default '',
  note text not null default '',
  active boolean not null default true,
  del_yn text not null default 'N',
  updated_by text not null default ''
);

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  no integer not null,
  gubun text not null,
  client text not null,
  name1 text not null,
  name2 text not null default '',
  supplier text not null default '',
  cost_price numeric null,
  sell_price numeric null,
  ea_per_b integer null,
  box_per_p integer null,
  ea_per_p integer null,
  pallets_per_truck integer null,
  del_yn text not null default 'N',
  updated_by text not null default ''
);

create table if not exists public.documents (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  issue_no text not null,
  client text not null,
  manager text not null default '',
  manager_tel text not null default '',
  receiver text not null default '',
  supplier_biz_no text not null default '',
  supplier_name text not null default '',
  supplier_owner text not null default '',
  supplier_address text not null default '',
  supplier_business_type text not null default '',
  supplier_business_item text not null default '',
  order_date date null,
  arrive_date date null,
  delivery_addr text not null default '',
  remark text not null default '',
  request_note text not null default '',
  total_supply numeric not null default 0,
  total_vat numeric not null default 0,
  total_amount numeric not null default 0,
  author text not null default '',
  status text not null default 'ST00',
  del_yn text not null default 'N',
  updated_by text not null default ''
);

create table if not exists public.document_items (
  id bigint generated by default as identity primary key,
  document_id uuid not null references public.documents(id) on delete cascade,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  seq integer not null,
  name1 text not null,
  name2 text not null default '',
  gubun text not null default '기타',
  qty integer not null default 0,
  unit_price numeric not null default 0,
  supply numeric not null default 0,
  vat boolean not null default true,
  order_date date null,
  arrive_date date null,
  item_note text not null default '',
  ea_per_b integer null,
  box_per_p integer null,
  custom_pallet numeric null,
  custom_box numeric null,
  del_yn text not null default 'N',
  updated_by text not null default ''
);

create table if not exists public.order_book (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  doc_id uuid null,
  issue_no text not null default '',
  date date null,
  deadline date null,
  client text not null default '',
  product text not null default '',
  qty integer not null default 0,
  note text not null default '',
  receipt text not null default '',
  status text not null default 'ST00',
  shipped_status text not null default '미출고',
  from_doc boolean not null default false,
  del_yn text not null default 'N',
  updated_by text not null default ''
);

do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'accounts_role_check'
  ) then
    alter table public.accounts
      add constraint accounts_role_check
      check (role in ('admin', 'user'));
  end if;

  if not exists (
    select 1 from pg_constraint where conname = 'accounts_del_yn_check'
  ) then
    alter table public.accounts
      add constraint accounts_del_yn_check
      check (del_yn in ('Y', 'N'));
  end if;

  if not exists (
    select 1 from pg_constraint where conname = 'clients_del_yn_check'
  ) then
    alter table public.clients
      add constraint clients_del_yn_check
      check (del_yn in ('Y', 'N'));
  end if;

  if not exists (
    select 1 from pg_constraint where conname = 'products_del_yn_check'
  ) then
    alter table public.products
      add constraint products_del_yn_check
      check (del_yn in ('Y', 'N'));
  end if;

  if not exists (
    select 1 from pg_constraint where conname = 'documents_status_check'
  ) then
    alter table public.documents
      add constraint documents_status_check
      check (status in ('ST00', 'ST01'));
  end if;

  if not exists (
    select 1 from pg_constraint where conname = 'documents_del_yn_check'
  ) then
    alter table public.documents
      add constraint documents_del_yn_check
      check (del_yn in ('Y', 'N'));
  end if;

  if not exists (
    select 1 from pg_constraint where conname = 'document_items_del_yn_check'
  ) then
    alter table public.document_items
      add constraint document_items_del_yn_check
      check (del_yn in ('Y', 'N'));
  end if;

  if not exists (
    select 1 from pg_constraint where conname = 'order_book_status_check'
  ) then
    alter table public.order_book
      add constraint order_book_status_check
      check (status in ('ST00', 'ST01'));
  end if;

  if not exists (
    select 1 from pg_constraint where conname = 'order_book_shipped_status_check'
  ) then
    alter table public.order_book
      add constraint order_book_shipped_status_check
      check (shipped_status in ('미출고', '출고'));
  end if;

  if not exists (
    select 1 from pg_constraint where conname = 'order_book_del_yn_check'
  ) then
    alter table public.order_book
      add constraint order_book_del_yn_check
      check (del_yn in ('Y', 'N'));
  end if;
end
$$;

create index if not exists idx_accounts_name on public.accounts (name);
create index if not exists idx_accounts_role on public.accounts (role);
create index if not exists idx_accounts_del_yn on public.accounts (del_yn);
create index if not exists idx_accounts_updated_at on public.accounts (updated_at desc);

create index if not exists idx_clients_name on public.clients (name);
create index if not exists idx_clients_active on public.clients (active);
create index if not exists idx_clients_del_yn on public.clients (del_yn);
create index if not exists idx_clients_updated_at on public.clients (updated_at desc);

create index if not exists idx_products_no on public.products (no);
create index if not exists idx_products_client on public.products (client);
create index if not exists idx_products_gubun on public.products (gubun);
create index if not exists idx_products_del_yn on public.products (del_yn);
create index if not exists idx_products_updated_at on public.products (updated_at desc);

create index if not exists idx_documents_created_at on public.documents (created_at desc);
create index if not exists idx_documents_issue_no on public.documents (issue_no);
create index if not exists idx_documents_status on public.documents (status);
create index if not exists idx_documents_del_yn on public.documents (del_yn);
create index if not exists idx_documents_updated_at on public.documents (updated_at desc);

create index if not exists idx_document_items_document_id on public.document_items (document_id);
create index if not exists idx_document_items_del_yn on public.document_items (del_yn);
create index if not exists idx_document_items_updated_at on public.document_items (updated_at desc);

create index if not exists idx_order_book_created_at on public.order_book (created_at desc);
create index if not exists idx_order_book_date on public.order_book (date desc);
create index if not exists idx_order_book_client on public.order_book (client);
create index if not exists idx_order_book_doc_id on public.order_book (doc_id);
create index if not exists idx_order_book_status on public.order_book (status);
create index if not exists idx_order_book_shipped_status on public.order_book (shipped_status);
create index if not exists idx_order_book_del_yn on public.order_book (del_yn);
create index if not exists idx_order_book_updated_at on public.order_book (updated_at desc);

create unique index if not exists uq_documents_active_issue_no
  on public.documents (issue_no)
  where del_yn = 'N';

create unique index if not exists uq_document_items_active_document_id_seq
  on public.document_items (document_id, seq)
  where del_yn = 'N';

insert into public.accounts (id, password, name, rank, tel, email, role, updated_by)
values ('admin', 'dkh2025!', '관리자', '', '', '', 'admin', 'system')
on conflict (id) do nothing;

alter table public.accounts enable row level security;
alter table public.clients enable row level security;
alter table public.products enable row level security;
alter table public.documents enable row level security;
alter table public.document_items enable row level security;
alter table public.order_book enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies where schemaname = 'public' and tablename = 'accounts' and policyname = 'accounts_select_anon'
  ) then
    create policy accounts_select_anon on public.accounts for select to anon using (true);
  end if;

  if not exists (
    select 1 from pg_policies where schemaname = 'public' and tablename = 'accounts' and policyname = 'accounts_insert_anon'
  ) then
    create policy accounts_insert_anon on public.accounts for insert to anon with check (true);
  end if;

  if not exists (
    select 1 from pg_policies where schemaname = 'public' and tablename = 'accounts' and policyname = 'accounts_update_anon'
  ) then
    create policy accounts_update_anon on public.accounts for update to anon using (true) with check (true);
  end if;

  if not exists (
    select 1 from pg_policies where schemaname = 'public' and tablename = 'accounts' and policyname = 'accounts_delete_anon'
  ) then
    create policy accounts_delete_anon on public.accounts for delete to anon using (true);
  end if;

  if not exists (
    select 1 from pg_policies where schemaname = 'public' and tablename = 'clients' and policyname = 'clients_select_anon'
  ) then
    create policy clients_select_anon on public.clients for select to anon using (true);
  end if;

  if not exists (
    select 1 from pg_policies where schemaname = 'public' and tablename = 'clients' and policyname = 'clients_insert_anon'
  ) then
    create policy clients_insert_anon on public.clients for insert to anon with check (true);
  end if;

  if not exists (
    select 1 from pg_policies where schemaname = 'public' and tablename = 'clients' and policyname = 'clients_update_anon'
  ) then
    create policy clients_update_anon on public.clients for update to anon using (true) with check (true);
  end if;

  if not exists (
    select 1 from pg_policies where schemaname = 'public' and tablename = 'clients' and policyname = 'clients_delete_anon'
  ) then
    create policy clients_delete_anon on public.clients for delete to anon using (true);
  end if;

  if not exists (
    select 1 from pg_policies where schemaname = 'public' and tablename = 'products' and policyname = 'products_select_anon'
  ) then
    create policy products_select_anon on public.products for select to anon using (true);
  end if;

  if not exists (
    select 1 from pg_policies where schemaname = 'public' and tablename = 'products' and policyname = 'products_insert_anon'
  ) then
    create policy products_insert_anon on public.products for insert to anon with check (true);
  end if;

  if not exists (
    select 1 from pg_policies where schemaname = 'public' and tablename = 'products' and policyname = 'products_update_anon'
  ) then
    create policy products_update_anon on public.products for update to anon using (true) with check (true);
  end if;

  if not exists (
    select 1 from pg_policies where schemaname = 'public' and tablename = 'products' and policyname = 'products_delete_anon'
  ) then
    create policy products_delete_anon on public.products for delete to anon using (true);
  end if;

  if not exists (
    select 1 from pg_policies where schemaname = 'public' and tablename = 'documents' and policyname = 'documents_select_anon'
  ) then
    create policy documents_select_anon on public.documents for select to anon using (true);
  end if;

  if not exists (
    select 1 from pg_policies where schemaname = 'public' and tablename = 'documents' and policyname = 'documents_insert_anon'
  ) then
    create policy documents_insert_anon on public.documents for insert to anon with check (true);
  end if;

  if not exists (
    select 1 from pg_policies where schemaname = 'public' and tablename = 'documents' and policyname = 'documents_update_anon'
  ) then
    create policy documents_update_anon on public.documents for update to anon using (true) with check (true);
  end if;

  if not exists (
    select 1 from pg_policies where schemaname = 'public' and tablename = 'document_items' and policyname = 'document_items_select_anon'
  ) then
    create policy document_items_select_anon on public.document_items for select to anon using (true);
  end if;

  if not exists (
    select 1 from pg_policies where schemaname = 'public' and tablename = 'document_items' and policyname = 'document_items_insert_anon'
  ) then
    create policy document_items_insert_anon on public.document_items for insert to anon with check (true);
  end if;

  if not exists (
    select 1 from pg_policies where schemaname = 'public' and tablename = 'document_items' and policyname = 'document_items_update_anon'
  ) then
    create policy document_items_update_anon on public.document_items for update to anon using (true) with check (true);
  end if;

  if not exists (
    select 1 from pg_policies where schemaname = 'public' and tablename = 'order_book' and policyname = 'order_book_select_anon'
  ) then
    create policy order_book_select_anon on public.order_book for select to anon using (true);
  end if;

  if not exists (
    select 1 from pg_policies where schemaname = 'public' and tablename = 'order_book' and policyname = 'order_book_insert_anon'
  ) then
    create policy order_book_insert_anon on public.order_book for insert to anon with check (true);
  end if;

  if not exists (
    select 1 from pg_policies where schemaname = 'public' and tablename = 'order_book' and policyname = 'order_book_update_anon'
  ) then
    create policy order_book_update_anon on public.order_book for update to anon using (true) with check (true);
  end if;

  if not exists (
    select 1 from pg_policies where schemaname = 'public' and tablename = 'order_book' and policyname = 'order_book_delete_anon'
  ) then
    create policy order_book_delete_anon on public.order_book for delete to anon using (true);
  end if;
end
$$;
