create table if not exists public.clients (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  name text not null,
  manager text not null default '',
  tel text not null default '',
  addr text not null default '',
  time text not null default '',
  lunch text not null default '',
  note text not null default '',
  active boolean not null default true,
  del_yn text not null default 'N',
  updated_by text not null default ''
);

do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'clients_del_yn_check'
  ) then
    alter table public.clients
      add constraint clients_del_yn_check
      check (del_yn in ('Y', 'N'));
  end if;
end
$$;

create index if not exists idx_clients_name on public.clients (name);
create index if not exists idx_clients_active on public.clients (active);
create index if not exists idx_clients_del_yn on public.clients (del_yn);
create index if not exists idx_clients_updated_at on public.clients (updated_at desc);
