create table if not exists public.products (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  no integer not null,
  gubun text not null,
  client text not null,
  name1 text not null,
  name2 text not null default '',
  supplier text not null default '',
  cost_price numeric null,
  sell_price numeric null,
  ea_per_b integer null,
  box_per_p integer null,
  ea_per_p integer null,
  pallets_per_truck integer null,
  del_yn text not null default 'N',
  updated_by text not null default '',
  constraint products_del_yn_check check (del_yn in ('Y', 'N'))
);

create index if not exists idx_products_no on public.products (no);
create index if not exists idx_products_client on public.products (client);
create index if not exists idx_products_gubun on public.products (gubun);
create index if not exists idx_products_del_yn on public.products (del_yn);
create index if not exists idx_products_updated_at on public.products (updated_at desc);
