create table if not exists public.documents (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  issue_no text not null,
  client text not null,
  manager text not null default '',
  manager_tel text not null default '',
  receiver text not null default '',
  supplier_biz_no text not null default '',
  supplier_name text not null default '',
  supplier_owner text not null default '',
  supplier_address text not null default '',
  supplier_business_type text not null default '',
  supplier_business_item text not null default '',
  order_date date null,
  arrive_date date null,
  delivery_addr text not null default '',
  remark text not null default '',
  request_note text not null default '',
  total_supply numeric not null default 0,
  total_vat numeric not null default 0,
  total_amount numeric not null default 0,
  author text not null default '',
  status text not null default 'ST00',
  del_yn text not null default 'N',
  updated_by text not null default ''
);

create table if not exists public.document_items (
  id bigint generated by default as identity primary key,
  document_id uuid not null references public.documents(id) on delete cascade,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  seq integer not null,
  name1 text not null,
  name2 text not null default '',
  gubun text not null default '기타',
  qty integer not null default 0,
  unit_price numeric not null default 0,
  supply numeric not null default 0,
  vat boolean not null default true,
  order_date date null,
  arrive_date date null,
  item_note text not null default '',
  ea_per_b integer null,
  box_per_p integer null,
  custom_pallet numeric null,
  custom_box numeric null,
  del_yn text not null default 'N',
  updated_by text not null default ''
);

do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'documents_status_check'
  ) then
    alter table public.documents
      add constraint documents_status_check
      check (status in ('ST00', 'ST01'));
  end if;

  if not exists (
    select 1 from pg_constraint where conname = 'documents_del_yn_check'
  ) then
    alter table public.documents
      add constraint documents_del_yn_check
      check (del_yn in ('Y', 'N'));
  end if;

  if not exists (
    select 1 from pg_constraint where conname = 'document_items_del_yn_check'
  ) then
    alter table public.document_items
      add constraint document_items_del_yn_check
      check (del_yn in ('Y', 'N'));
  end if;
end
$$;

create index if not exists idx_documents_created_at on public.documents (created_at desc);
create index if not exists idx_documents_issue_no on public.documents (issue_no);
create index if not exists idx_documents_status on public.documents (status);
create index if not exists idx_documents_del_yn on public.documents (del_yn);
create index if not exists idx_documents_updated_at on public.documents (updated_at desc);

create index if not exists idx_document_items_document_id on public.document_items (document_id);
create index if not exists idx_document_items_del_yn on public.document_items (del_yn);
create index if not exists idx_document_items_updated_at on public.document_items (updated_at desc);

create unique index if not exists uq_documents_active_issue_no
  on public.documents (issue_no)
  where del_yn = 'N';

create unique index if not exists uq_document_items_active_document_id_seq
  on public.document_items (document_id, seq)
  where del_yn = 'N';
