create table if not exists public.product_masters (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  gubun text not null,
  name1 text not null,
  name2 text not null default '',
  del_yn text not null default 'N',
  updated_by text not null default ''
);

alter table public.products
  add column if not exists product_master_id bigint null;

do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'product_masters_del_yn_check'
  ) then
    alter table public.product_masters
      add constraint product_masters_del_yn_check
      check (del_yn in ('Y', 'N'));
  end if;

  if not exists (
    select 1 from pg_constraint where conname = 'products_product_master_id_fkey'
  ) then
    alter table public.products
      add constraint products_product_master_id_fkey
      foreign key (product_master_id) references public.product_masters(id);
  end if;
end
$$;

create index if not exists idx_product_masters_name1 on public.product_masters (name1);
create index if not exists idx_product_masters_gubun on public.product_masters (gubun);
create index if not exists idx_product_masters_del_yn on public.product_masters (del_yn);
create index if not exists idx_products_product_master_id on public.products (product_master_id);

alter table public.product_masters enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'product_masters'
      and policyname = 'product_masters_select_anon'
  ) then
    create policy product_masters_select_anon
      on public.product_masters
      for select
      to anon
      using (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'product_masters'
      and policyname = 'product_masters_insert_anon'
  ) then
    create policy product_masters_insert_anon
      on public.product_masters
      for insert
      to anon
      with check (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'product_masters'
      and policyname = 'product_masters_update_anon'
  ) then
    create policy product_masters_update_anon
      on public.product_masters
      for update
      to anon
      using (true)
      with check (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'product_masters'
      and policyname = 'product_masters_delete_anon'
  ) then
    create policy product_masters_delete_anon
      on public.product_masters
      for delete
      to anon
      using (true);
  end if;
end
$$;
