create table if not exists public.suppliers (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  name text not null,
  biz_no text not null default '',
  owner text not null default '',
  address text not null default '',
  business_type text not null default '',
  business_item text not null default '',
  active boolean not null default true,
  del_yn text not null default 'N',
  updated_by text not null default ''
);

do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'suppliers_del_yn_check'
  ) then
    alter table public.suppliers
      add constraint suppliers_del_yn_check
      check (del_yn in ('Y', 'N'));
  end if;
end
$$;

create index if not exists idx_suppliers_name on public.suppliers (name);
create index if not exists idx_suppliers_active on public.suppliers (active);
create index if not exists idx_suppliers_del_yn on public.suppliers (del_yn);
create index if not exists idx_suppliers_updated_at on public.suppliers (updated_at desc);
