create table if not exists public.price_change_logs (
  id bigint generated by default as identity primary key,
  changed_at timestamptz not null default now(),
  changed_by text not null default '',
  document_item_id bigint null,
  document_id uuid null,
  issue_no text not null default '',
  base_date date null,
  date_from date null,
  date_to date null,
  client_id bigint null,
  client_name text not null default '',
  receiver text not null default '',
  product_id bigint null,
  product_name text not null default '',
  old_cost_price numeric null,
  new_cost_price numeric null,
  old_unit_price numeric null,
  new_unit_price numeric null,
  changed_item_count integer not null default 0,
  changed_document_count integer not null default 0
);

alter table public.price_change_logs
  add column if not exists document_item_id bigint null,
  add column if not exists document_id uuid null,
  add column if not exists issue_no text not null default '',
  add column if not exists base_date date null;

create index if not exists idx_price_change_logs_changed_at
  on public.price_change_logs (changed_at desc);

create index if not exists idx_price_change_logs_base_date
  on public.price_change_logs (base_date desc);

create index if not exists idx_price_change_logs_document_item_id
  on public.price_change_logs (document_item_id);

alter table public.price_change_logs enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'price_change_logs'
      and policyname = 'price_change_logs_select_anon'
  ) then
    create policy price_change_logs_select_anon
      on public.price_change_logs
      for select
      to anon
      using (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'price_change_logs'
      and policyname = 'price_change_logs_insert_anon'
  ) then
    create policy price_change_logs_insert_anon
      on public.price_change_logs
      for insert
      to anon
      with check (true);
  end if;
end
$$;

create or replace function public.preview_document_item_price_change(
  p_date_from date default null,
  p_date_to date default null,
  p_client_id bigint default null,
  p_receiver text default null,
  p_product_id bigint default null,
  p_product_name text default null
)
returns table (
  item_id bigint,
  document_id uuid,
  issue_no text,
  base_date date,
  client_id bigint,
  client_name text,
  receiver text,
  product_id bigint,
  product_name text,
  qty integer,
  cost_price numeric,
  unit_price numeric,
  supply numeric,
  vat boolean
)
language sql
stable
as $$
  select
    di.id as item_id,
    d.id as document_id,
    d.issue_no,
    coalesce(di.arrive_date, d.arrive_date, di.order_date, d.order_date) as base_date,
    d.client_id,
    d.client as client_name,
    d.receiver,
    di.product_id,
    di.name1 as product_name,
    di.qty,
    di.cost_price,
    di.unit_price,
    di.supply,
    di.vat
  from public.document_items di
  join public.documents d on d.id = di.document_id
  where d.del_yn = 'N'
    and di.del_yn = 'N'
    and coalesce(d.status, '') <> 'ST01'
    and (p_date_from is null or coalesce(di.arrive_date, d.arrive_date, di.order_date, d.order_date) >= p_date_from)
    and (p_date_to is null or coalesce(di.arrive_date, d.arrive_date, di.order_date, d.order_date) <= p_date_to)
    and (p_client_id is null or d.client_id = p_client_id)
    and (nullif(trim(p_receiver), '') is null or d.receiver = trim(p_receiver))
    and (
      (trim(coalesce(p_product_name, '')) = '__manual__' and di.product_id is null)
      or (trim(coalesce(p_product_name, '')) <> '__manual__' and (p_product_id is null or di.product_id = p_product_id))
    )
    and (
      trim(coalesce(p_product_name, '')) = '__manual__'
      or nullif(trim(p_product_name), '') is null
      or di.name1 = trim(p_product_name)
      or di.name2 = trim(p_product_name)
    )
  order by base_date, d.issue_no, di.seq, di.id;
$$;

create or replace function public.apply_document_item_price_change(
  p_item_ids bigint[],
  p_new_cost_price numeric default null,
  p_new_unit_price numeric default null,
  p_changed_by text default '',
  p_date_from date default null,
  p_date_to date default null,
  p_client_id bigint default null,
  p_client_name text default '',
  p_receiver text default '',
  p_product_id bigint default null,
  p_product_name text default ''
)
returns table (
  log_id bigint,
  changed_item_count integer,
  changed_document_count integer
)
language plpgsql
as $$
declare
  v_log_id bigint;
  v_changed_item_count integer;
  v_changed_document_count integer;
begin
  if p_item_ids is null or cardinality(p_item_ids) = 0 then
    raise exception 'No document items selected for price change.';
  end if;

  if p_new_cost_price is null and p_new_unit_price is null then
    raise exception 'New cost price or unit price is required.';
  end if;

  create temporary table tmp_price_change_targets on commit drop as
  select
    di.id,
    di.document_id,
    d.issue_no,
    coalesce(di.arrive_date, d.arrive_date, di.order_date, d.order_date) as base_date,
    d.client_id,
    d.client as client_name,
    d.receiver,
    di.product_id,
    di.name1 as product_name,
    di.cost_price,
    di.unit_price
  from public.document_items di
  join public.documents d on d.id = di.document_id
  where di.id = any(p_item_ids)
    and di.del_yn = 'N'
    and d.del_yn = 'N'
    and coalesce(d.status, '') <> 'ST01';

  select count(*), count(distinct document_id)
  into v_changed_item_count, v_changed_document_count
  from tmp_price_change_targets;

  if v_changed_item_count = 0 then
    raise exception 'No active document items matched selected ids.';
  end if;

  update public.document_items di
  set
    cost_price = case when p_new_cost_price is null then di.cost_price else p_new_cost_price end,
    unit_price = case when p_new_unit_price is null then di.unit_price else p_new_unit_price end,
    supply = case when p_new_unit_price is null then di.supply else di.qty * p_new_unit_price end,
    updated_at = now(),
    updated_by = coalesce(nullif(trim(p_changed_by), ''), 'system')
  from tmp_price_change_targets t
  where di.id = t.id;

  if p_new_unit_price is not null then
    with affected_documents as (
      select distinct document_id from tmp_price_change_targets
    ),
    totals as (
      select
        di.document_id,
        coalesce(sum(di.supply), 0) as total_supply,
        coalesce(sum(case when di.vat then round(di.supply * 0.1) else 0 end), 0) as total_vat
      from public.document_items di
      join affected_documents ad on ad.document_id = di.document_id
      where di.del_yn = 'N'
      group by di.document_id
    )
    update public.documents d
    set
      total_supply = totals.total_supply,
      total_vat = totals.total_vat,
      total_amount = totals.total_supply + totals.total_vat,
      updated_at = now(),
      updated_by = coalesce(nullif(trim(p_changed_by), ''), 'system')
    from totals
    where d.id = totals.document_id
      and d.del_yn = 'N';
  end if;

  with inserted as (
    insert into public.price_change_logs (
      changed_by,
      document_item_id,
      document_id,
      issue_no,
      base_date,
      date_from,
      date_to,
      client_id,
      client_name,
      receiver,
      product_id,
      product_name,
      old_cost_price,
      new_cost_price,
      old_unit_price,
      new_unit_price,
      changed_item_count,
      changed_document_count
    )
    select
      coalesce(nullif(trim(p_changed_by), ''), 'system'),
      t.id,
      t.document_id,
      coalesce(t.issue_no, ''),
      t.base_date,
      p_date_from,
      p_date_to,
      t.client_id,
      coalesce(t.client_name, ''),
      coalesce(t.receiver, ''),
      t.product_id,
      coalesce(t.product_name, ''),
      case when p_new_cost_price is null then null else t.cost_price end,
      p_new_cost_price,
      case when p_new_unit_price is null then null else t.unit_price end,
      p_new_unit_price,
      1,
      1
    from tmp_price_change_targets t
    order by t.base_date, t.issue_no, t.id
    returning id
  )
  select min(id) into v_log_id from inserted;

  return query select v_log_id, v_changed_item_count, v_changed_document_count;
end;
$$;
