create table if not exists public.clients (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  name text not null,
  manager text not null default '',
  tel text not null default '',
  addr text not null default '',
  time text not null default '',
  lunch text not null default '',
  note text not null default '',
  active boolean not null default true,
  del_yn text not null default 'N',
  updated_by text not null default ''
);

alter table public.clients add column if not exists created_at timestamptz not null default now();
alter table public.clients add column if not exists updated_at timestamptz not null default now();
alter table public.clients add column if not exists name text;
alter table public.clients add column if not exists manager text not null default '';
alter table public.clients add column if not exists tel text not null default '';
alter table public.clients add column if not exists addr text not null default '';
alter table public.clients add column if not exists time text not null default '';
alter table public.clients add column if not exists lunch text not null default '';
alter table public.clients add column if not exists note text not null default '';
alter table public.clients add column if not exists active boolean not null default true;
alter table public.clients add column if not exists del_yn text not null default 'N';
alter table public.clients add column if not exists updated_by text not null default '';

update public.clients
set
  name = coalesce(name, ''),
  del_yn = coalesce(nullif(del_yn, ''), 'N'),
  updated_at = coalesce(updated_at, created_at, now()),
  updated_by = coalesce(nullif(updated_by, ''), 'system')
where name is null
   or del_yn is null
   or del_yn = ''
   or updated_at is null
   or updated_by is null
   or updated_by = '';

alter table public.clients alter column name set not null;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'clients_del_yn_check'
  ) then
    alter table public.clients
      add constraint clients_del_yn_check
      check (del_yn in ('Y', 'N'));
  end if;
end
$$;

create index if not exists idx_clients_name on public.clients (name);
create index if not exists idx_clients_active on public.clients (active);
create index if not exists idx_clients_del_yn on public.clients (del_yn);
create index if not exists idx_clients_updated_at on public.clients (updated_at desc);

alter table public.clients enable row level security;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'clients'
      and policyname = 'clients_select_anon'
  ) then
    create policy clients_select_anon
      on public.clients
      for select
      to anon
      using (true);
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'clients'
      and policyname = 'clients_insert_anon'
  ) then
    create policy clients_insert_anon
      on public.clients
      for insert
      to anon
      with check (true);
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'clients'
      and policyname = 'clients_update_anon'
  ) then
    create policy clients_update_anon
      on public.clients
      for update
      to anon
      using (true)
      with check (true);
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'clients'
      and policyname = 'clients_delete_anon'
  ) then
    create policy clients_delete_anon
      on public.clients
      for delete
      to anon
      using (true);
  end if;
end
$$;
