create table if not exists public.clients (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  name text not null,
  manager text not null default '',
  tel text not null default '',
  addr text not null default '',
  time text not null default '',
  lunch text not null default '',
  note text not null default '',
  active boolean not null default true
);

alter table public.clients add column if not exists created_at timestamptz not null default now();
alter table public.clients add column if not exists name text;
alter table public.clients add column if not exists manager text not null default '';
alter table public.clients add column if not exists tel text not null default '';
alter table public.clients add column if not exists addr text not null default '';
alter table public.clients add column if not exists time text not null default '';
alter table public.clients add column if not exists lunch text not null default '';
alter table public.clients add column if not exists note text not null default '';
alter table public.clients add column if not exists active boolean not null default true;

update public.clients
set name = coalesce(name, '')
where name is null;

alter table public.clients alter column name set not null;

create index if not exists idx_clients_name on public.clients (name);
create index if not exists idx_clients_active on public.clients (active);

alter table public.clients enable row level security;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'clients'
      and policyname = 'clients_select_anon'
  ) then
    create policy clients_select_anon
      on public.clients
      for select
      to anon
      using (true);
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'clients'
      and policyname = 'clients_insert_anon'
  ) then
    create policy clients_insert_anon
      on public.clients
      for insert
      to anon
      with check (true);
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'clients'
      and policyname = 'clients_update_anon'
  ) then
    create policy clients_update_anon
      on public.clients
      for update
      to anon
      using (true)
      with check (true);
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'clients'
      and policyname = 'clients_delete_anon'
  ) then
    create policy clients_delete_anon
      on public.clients
      for delete
      to anon
      using (true);
  end if;
end
$$;
