create extension if not exists "pgcrypto";

create table if not exists public.documents (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  issue_no text not null,
  client text not null,
  manager text not null default '',
  manager_tel text not null default '',
  receiver text not null default '',
  order_date date null,
  arrive_date date null,
  delivery_addr text not null default '',
  remark text not null default '',
  request_note text not null default '',
  total_supply numeric not null default 0,
  total_vat numeric not null default 0,
  total_amount numeric not null default 0,
  author text not null default '',
  cancelled boolean not null default false
);

create table if not exists public.document_items (
  id bigint generated by default as identity primary key,
  document_id uuid not null references public.documents(id) on delete cascade,
  seq integer not null,
  name1 text not null,
  name2 text not null default '',
  gubun text not null default '기타',
  qty integer not null default 0,
  unit_price numeric not null default 0,
  supply numeric not null default 0,
  vat boolean not null default true,
  order_date date null,
  arrive_date date null,
  item_note text not null default '',
  ea_per_b integer null,
  box_per_p integer null,
  custom_pallet numeric null,
  custom_box numeric null
);

alter table public.documents add column if not exists created_at timestamptz not null default now();
alter table public.documents add column if not exists updated_at timestamptz not null default now();
alter table public.documents add column if not exists issue_no text;
alter table public.documents add column if not exists client text;
alter table public.documents add column if not exists manager text not null default '';
alter table public.documents add column if not exists manager_tel text not null default '';
alter table public.documents add column if not exists receiver text not null default '';
alter table public.documents add column if not exists order_date date null;
alter table public.documents add column if not exists arrive_date date null;
alter table public.documents add column if not exists delivery_addr text not null default '';
alter table public.documents add column if not exists remark text not null default '';
alter table public.documents add column if not exists request_note text not null default '';
alter table public.documents add column if not exists total_supply numeric not null default 0;
alter table public.documents add column if not exists total_vat numeric not null default 0;
alter table public.documents add column if not exists total_amount numeric not null default 0;
alter table public.documents add column if not exists author text not null default '';
alter table public.documents add column if not exists cancelled boolean not null default false;

alter table public.document_items add column if not exists seq integer;
alter table public.document_items add column if not exists name1 text;
alter table public.document_items add column if not exists name2 text not null default '';
alter table public.document_items add column if not exists gubun text not null default '기타';
alter table public.document_items add column if not exists qty integer not null default 0;
alter table public.document_items add column if not exists unit_price numeric not null default 0;
alter table public.document_items add column if not exists supply numeric not null default 0;
alter table public.document_items add column if not exists vat boolean not null default true;
alter table public.document_items add column if not exists order_date date null;
alter table public.document_items add column if not exists arrive_date date null;
alter table public.document_items add column if not exists item_note text not null default '';
alter table public.document_items add column if not exists ea_per_b integer null;
alter table public.document_items add column if not exists box_per_p integer null;
alter table public.document_items add column if not exists custom_pallet numeric null;
alter table public.document_items add column if not exists custom_box numeric null;

update public.documents
set
  issue_no = coalesce(issue_no, ''),
  client = coalesce(client, '')
where issue_no is null or client is null;

alter table public.documents alter column issue_no set not null;
alter table public.documents alter column client set not null;

create index if not exists idx_documents_created_at on public.documents (created_at desc);
create index if not exists idx_documents_issue_no on public.documents (issue_no);
create index if not exists idx_document_items_document_id on public.document_items (document_id);

alter table public.documents enable row level security;
alter table public.document_items enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies where schemaname = 'public' and tablename = 'documents' and policyname = 'documents_select_anon'
  ) then
    create policy documents_select_anon on public.documents for select to anon using (true);
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1 from pg_policies where schemaname = 'public' and tablename = 'documents' and policyname = 'documents_insert_anon'
  ) then
    create policy documents_insert_anon on public.documents for insert to anon with check (true);
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1 from pg_policies where schemaname = 'public' and tablename = 'document_items' and policyname = 'document_items_select_anon'
  ) then
    create policy document_items_select_anon on public.document_items for select to anon using (true);
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1 from pg_policies where schemaname = 'public' and tablename = 'document_items' and policyname = 'document_items_insert_anon'
  ) then
    create policy document_items_insert_anon on public.document_items for insert to anon with check (true);
  end if;
end
$$;
