create table if not exists public.products (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  no integer not null,
  gubun text not null,
  client text not null,
  name1 text not null,
  name2 text not null default '',
  supplier text not null default '',
  cost_price numeric null,
  sell_price numeric null,
  ea_per_b integer null,
  box_per_p integer null,
  ea_per_p integer null,
  pallets_per_truck integer null
);

alter table public.products add column if not exists created_at timestamptz not null default now();
alter table public.products add column if not exists no integer;
alter table public.products add column if not exists gubun text;
alter table public.products add column if not exists client text;
alter table public.products add column if not exists name1 text;
alter table public.products add column if not exists name2 text not null default '';
alter table public.products add column if not exists supplier text not null default '';
alter table public.products add column if not exists cost_price numeric null;
alter table public.products add column if not exists sell_price numeric null;
alter table public.products add column if not exists ea_per_b integer null;
alter table public.products add column if not exists box_per_p integer null;
alter table public.products add column if not exists ea_per_p integer null;
alter table public.products add column if not exists pallets_per_truck integer null;

update public.products
set
  gubun = coalesce(gubun, ''),
  client = coalesce(client, ''),
  name1 = coalesce(name1, ''),
  name2 = coalesce(name2, ''),
  supplier = coalesce(supplier, '')
where
  gubun is null
  or client is null
  or name1 is null
  or name2 is null
  or supplier is null;

alter table public.products alter column no set not null;
alter table public.products alter column gubun set not null;
alter table public.products alter column client set not null;
alter table public.products alter column name1 set not null;

create index if not exists idx_products_no on public.products (no);
create index if not exists idx_products_client on public.products (client);
create index if not exists idx_products_gubun on public.products (gubun);

alter table public.products enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'products'
      and policyname = 'products_select_anon'
  ) then
    create policy products_select_anon
      on public.products
      for select
      to anon
      using (true);
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'products'
      and policyname = 'products_insert_anon'
  ) then
    create policy products_insert_anon
      on public.products
      for insert
      to anon
      with check (true);
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'products'
      and policyname = 'products_update_anon'
  ) then
    create policy products_update_anon
      on public.products
      for update
      to anon
      using (true)
      with check (true);
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'products'
      and policyname = 'products_delete_anon'
  ) then
    create policy products_delete_anon
      on public.products
      for delete
      to anon
      using (true);
  end if;
end
$$;
