create table if not exists public.document_items (
  id bigint generated by default as identity primary key,
  document_id uuid not null references public.documents(id) on delete cascade,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  seq integer not null,
  name1 text not null,
  name2 text not null default '',
  gubun text not null default '기타',
  qty integer not null default 0,
  unit_price numeric not null default 0,
  supply numeric not null default 0,
  vat boolean not null default true,
  order_date date null,
  arrive_date date null,
  item_note text not null default '',
  ea_per_b integer null,
  box_per_p integer null,
  custom_pallet numeric null,
  custom_box numeric null,
  del_yn text not null default 'N',
  updated_by text not null default '',
  constraint document_items_del_yn_check check (del_yn in ('Y', 'N'))
);

create index if not exists idx_document_items_document_id on public.document_items (document_id);
create index if not exists idx_document_items_del_yn on public.document_items (del_yn);
create index if not exists idx_document_items_updated_at on public.document_items (updated_at desc);
