alter table public.accounts
  add column if not exists department text not null default '',
  add column if not exists position text not null default '',
  add column if not exists job_title text not null default '',
  add column if not exists manager_id text null,
  add column if not exists can_approve boolean not null default false,
  add column if not exists approval_limit numeric null;

do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'accounts_manager_id_fkey'
  ) then
    alter table public.accounts
      add constraint accounts_manager_id_fkey
      foreign key (manager_id) references public.accounts(id);
  end if;
end
$$;

create index if not exists idx_accounts_department on public.accounts (department);
create index if not exists idx_accounts_manager_id on public.accounts (manager_id);
create index if not exists idx_accounts_can_approve on public.accounts (can_approve);

alter table public.documents
  add column if not exists approval_title text not null default '',
  add column if not exists approval_status text not null default 'draft',
  add column if not exists approval_requested_at timestamptz null,
  add column if not exists approval_completed_at timestamptz null,
  add column if not exists approval_current_step integer not null default 0;

do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'documents_approval_status_check'
  ) then
    alter table public.documents
      add constraint documents_approval_status_check
      check (approval_status in ('draft', 'pending', 'in_review', 'approved', 'rejected', 'cancelled'));
  end if;
end
$$;

create index if not exists idx_documents_approval_status on public.documents (approval_status);
create index if not exists idx_documents_approval_requested_at on public.documents (approval_requested_at desc);

create table if not exists public.approvals (
  id uuid primary key default gen_random_uuid(),
  target_type text not null default 'document',
  target_id text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  request_no text not null default '',
  title text not null default '',
  requester_id text not null default '',
  requester_name text not null default '',
  requester_rank text not null default '',
  requester_department text not null default '',
  requester_snapshot jsonb not null default '{}'::jsonb,
  status text not null default 'pending',
  current_step integer not null default 1,
  final_step integer not null default 1,
  requested_at timestamptz not null default now(),
  completed_at timestamptz null,
  rejected_at timestamptz null,
  cancelled_at timestamptz null,
  comment text not null default '',
  is_active boolean not null default true,
  del_yn text not null default 'N',
  updated_by text not null default ''
);

create table if not exists public.approval_steps (
  id bigint generated by default as identity primary key,
  approval_id uuid not null references public.approvals(id) on delete cascade,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  step_order integer not null,
  approver_id text not null default '',
  approver_name text not null default '',
  approver_rank text not null default '',
  approver_department text not null default '',
  approver_snapshot jsonb not null default '{}'::jsonb,
  approval_type text not null default 'approve',
  status text not null default 'waiting',
  acted_at timestamptz null,
  comment text not null default '',
  delegated_from text not null default '',
  del_yn text not null default 'N',
  updated_by text not null default ''
);

create table if not exists public.approval_events (
  id bigint generated by default as identity primary key,
  approval_id uuid not null references public.approvals(id) on delete cascade,
  step_id bigint null references public.approval_steps(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  actor_id text not null default '',
  actor_name text not null default '',
  actor_snapshot jsonb not null default '{}'::jsonb,
  event_type text not null default 'submitted',
  event_comment text not null default '',
  del_yn text not null default 'N',
  updated_by text not null default ''
);

do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'approvals_status_check'
  ) then
    alter table public.approvals
      add constraint approvals_status_check
      check (status in ('pending', 'in_review', 'approved', 'rejected', 'cancelled'));
  end if;

  if not exists (
    select 1 from pg_constraint where conname = 'approvals_del_yn_check'
  ) then
    alter table public.approvals
      add constraint approvals_del_yn_check
      check (del_yn in ('Y', 'N'));
  end if;

  if not exists (
    select 1 from pg_constraint where conname = 'approvals_target_type_check'
  ) then
    alter table public.approvals
      add constraint approvals_target_type_check
      check (target_type in ('document', 'expense', 'leave', 'purchase', 'generic'));
  end if;

  if not exists (
    select 1 from pg_constraint where conname = 'approval_steps_type_check'
  ) then
    alter table public.approval_steps
      add constraint approval_steps_type_check
      check (approval_type in ('approve', 'agree', 'review', 'final'));
  end if;

  if not exists (
    select 1 from pg_constraint where conname = 'approval_steps_status_check'
  ) then
    alter table public.approval_steps
      add constraint approval_steps_status_check
      check (status in ('waiting', 'pending', 'approved', 'rejected', 'skipped', 'cancelled'));
  end if;

  if not exists (
    select 1 from pg_constraint where conname = 'approval_steps_del_yn_check'
  ) then
    alter table public.approval_steps
      add constraint approval_steps_del_yn_check
      check (del_yn in ('Y', 'N'));
  end if;

  if not exists (
    select 1 from pg_constraint where conname = 'approval_events_type_check'
  ) then
    alter table public.approval_events
      add constraint approval_events_type_check
      check (event_type in ('submitted', 'approved', 'rejected', 'recalled', 'cancelled', 'commented', 'skipped', 'resubmitted'));
  end if;

  if not exists (
    select 1 from pg_constraint where conname = 'approval_events_del_yn_check'
  ) then
    alter table public.approval_events
      add constraint approval_events_del_yn_check
      check (del_yn in ('Y', 'N'));
  end if;
end
$$;

create index if not exists idx_approvals_target_type on public.approvals (target_type);
create index if not exists idx_approvals_target_id on public.approvals (target_id);
create index if not exists idx_approvals_status on public.approvals (status);
create index if not exists idx_approvals_requester_id on public.approvals (requester_id);
create index if not exists idx_approvals_requested_at on public.approvals (requested_at desc);
create index if not exists idx_approvals_del_yn on public.approvals (del_yn);

create index if not exists idx_approval_steps_approval_id on public.approval_steps (approval_id);
create index if not exists idx_approval_steps_approver_id on public.approval_steps (approver_id);
create index if not exists idx_approval_steps_status on public.approval_steps (status);
create index if not exists idx_approval_steps_del_yn on public.approval_steps (del_yn);

create index if not exists idx_approval_events_approval_id on public.approval_events (approval_id);
create index if not exists idx_approval_events_event_type on public.approval_events (event_type);
create index if not exists idx_approval_events_created_at on public.approval_events (created_at desc);
create index if not exists idx_approval_events_del_yn on public.approval_events (del_yn);

create unique index if not exists uq_approvals_active_target
  on public.approvals (target_type, target_id)
  where del_yn = 'N' and is_active = true;

create unique index if not exists uq_approval_steps_active_order
  on public.approval_steps (approval_id, step_order)
  where del_yn = 'N';
