create extension if not exists "pgcrypto";

create table if not exists public.documents (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  issue_no text not null,
  client text not null,
  manager text not null default '',
  manager_tel text not null default '',
  receiver text not null default '',
  supplier_biz_no text not null default '',
  supplier_name text not null default '',
  supplier_owner text not null default '',
  supplier_address text not null default '',
  supplier_business_type text not null default '',
  supplier_business_item text not null default '',
  order_date date null,
  arrive_date date null,
  delivery_addr text not null default '',
  remark text not null default '',
  request_note text not null default '',
  total_supply numeric not null default 0,
  total_vat numeric not null default 0,
  total_amount numeric not null default 0,
  author text not null default '',
  status text not null default 'ST00',
  del_yn text not null default 'N',
  updated_by text not null default ''
);

create table if not exists public.document_items (
  id bigint generated by default as identity primary key,
  document_id uuid not null references public.documents(id) on delete cascade,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  seq integer not null,
  name1 text not null,
  name2 text not null default '',
  gubun text not null default '기타',
  qty integer not null default 0,
  unit_price numeric not null default 0,
  supply numeric not null default 0,
  vat boolean not null default true,
  order_date date null,
  arrive_date date null,
  item_note text not null default '',
  ea_per_b integer null,
  box_per_p integer null,
  custom_pallet numeric null,
  custom_box numeric null,
  del_yn text not null default 'N',
  updated_by text not null default ''
);

alter table public.documents add column if not exists created_at timestamptz not null default now();
alter table public.documents add column if not exists updated_at timestamptz not null default now();
alter table public.documents add column if not exists issue_no text;
alter table public.documents add column if not exists client text;
alter table public.documents add column if not exists manager text not null default '';
alter table public.documents add column if not exists manager_tel text not null default '';
alter table public.documents add column if not exists receiver text not null default '';
alter table public.documents add column if not exists supplier_biz_no text not null default '';
alter table public.documents add column if not exists supplier_name text not null default '';
alter table public.documents add column if not exists supplier_owner text not null default '';
alter table public.documents add column if not exists supplier_address text not null default '';
alter table public.documents add column if not exists supplier_business_type text not null default '';
alter table public.documents add column if not exists supplier_business_item text not null default '';
alter table public.documents add column if not exists order_date date null;
alter table public.documents add column if not exists arrive_date date null;
alter table public.documents add column if not exists delivery_addr text not null default '';
alter table public.documents add column if not exists remark text not null default '';
alter table public.documents add column if not exists request_note text not null default '';
alter table public.documents add column if not exists total_supply numeric not null default 0;
alter table public.documents add column if not exists total_vat numeric not null default 0;
alter table public.documents add column if not exists total_amount numeric not null default 0;
alter table public.documents add column if not exists author text not null default '';
alter table public.documents add column if not exists status text not null default 'ST00';
alter table public.documents add column if not exists del_yn text not null default 'N';
alter table public.documents add column if not exists updated_by text not null default '';

alter table public.document_items add column if not exists created_at timestamptz not null default now();
alter table public.document_items add column if not exists updated_at timestamptz not null default now();
alter table public.document_items add column if not exists seq integer;
alter table public.document_items add column if not exists name1 text;
alter table public.document_items add column if not exists name2 text not null default '';
alter table public.document_items add column if not exists gubun text not null default '기타';
alter table public.document_items add column if not exists qty integer not null default 0;
alter table public.document_items add column if not exists unit_price numeric not null default 0;
alter table public.document_items add column if not exists supply numeric not null default 0;
alter table public.document_items add column if not exists vat boolean not null default true;
alter table public.document_items add column if not exists order_date date null;
alter table public.document_items add column if not exists arrive_date date null;
alter table public.document_items add column if not exists item_note text not null default '';
alter table public.document_items add column if not exists ea_per_b integer null;
alter table public.document_items add column if not exists box_per_p integer null;
alter table public.document_items add column if not exists custom_pallet numeric null;
alter table public.document_items add column if not exists custom_box numeric null;
alter table public.document_items add column if not exists del_yn text not null default 'N';
alter table public.document_items add column if not exists updated_by text not null default '';

update public.documents
set
  issue_no = coalesce(issue_no, ''),
  client = coalesce(client, ''),
  supplier_biz_no = coalesce(supplier_biz_no, ''),
  supplier_name = coalesce(supplier_name, ''),
  supplier_owner = coalesce(supplier_owner, ''),
  supplier_address = coalesce(supplier_address, ''),
  supplier_business_type = coalesce(supplier_business_type, ''),
  supplier_business_item = coalesce(supplier_business_item, ''),
  status = coalesce(nullif(status, ''), 'ST00'),
  del_yn = coalesce(nullif(del_yn, ''), 'N'),
  updated_at = coalesce(updated_at, created_at, now()),
  updated_by = coalesce(nullif(updated_by, ''), coalesce(nullif(author, ''), 'system'))
where issue_no is null
   or client is null
   or status is null
   or status = ''
   or del_yn is null
   or del_yn = ''
   or updated_at is null
   or updated_by is null
   or updated_by = '';

update public.document_items
set
  del_yn = coalesce(nullif(del_yn, ''), 'N'),
  created_at = coalesce(created_at, now()),
  updated_at = coalesce(updated_at, created_at, now()),
  updated_by = coalesce(nullif(updated_by, ''), 'system')
where del_yn is null
   or del_yn = ''
   or created_at is null
   or updated_at is null
   or updated_by is null
   or updated_by = '';

alter table public.documents alter column issue_no set not null;
alter table public.documents alter column client set not null;

do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'documents_status_check'
  ) then
    alter table public.documents
      add constraint documents_status_check
      check (status in ('ST00', 'ST01'));
  end if;

  if not exists (
    select 1 from pg_constraint where conname = 'documents_del_yn_check'
  ) then
    alter table public.documents
      add constraint documents_del_yn_check
      check (del_yn in ('Y', 'N'));
  end if;

  if not exists (
    select 1 from pg_constraint where conname = 'document_items_del_yn_check'
  ) then
    alter table public.document_items
      add constraint document_items_del_yn_check
      check (del_yn in ('Y', 'N'));
  end if;
end
$$;

create index if not exists idx_documents_created_at on public.documents (created_at desc);
create index if not exists idx_documents_issue_no on public.documents (issue_no);
create index if not exists idx_documents_status on public.documents (status);
create index if not exists idx_document_items_document_id on public.document_items (document_id);
create index if not exists idx_documents_del_yn on public.documents (del_yn);
create index if not exists idx_documents_updated_at_v2 on public.documents (updated_at desc);
create index if not exists idx_document_items_del_yn on public.document_items (del_yn);
create index if not exists idx_document_items_updated_at on public.document_items (updated_at desc);

alter table public.documents enable row level security;
alter table public.document_items enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies where schemaname = 'public' and tablename = 'documents' and policyname = 'documents_select_anon'
  ) then
    create policy documents_select_anon on public.documents for select to anon using (true);
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1 from pg_policies where schemaname = 'public' and tablename = 'documents' and policyname = 'documents_insert_anon'
  ) then
    create policy documents_insert_anon on public.documents for insert to anon with check (true);
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1 from pg_policies where schemaname = 'public' and tablename = 'documents' and policyname = 'documents_update_anon'
  ) then
    create policy documents_update_anon on public.documents for update to anon using (true) with check (true);
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1 from pg_policies where schemaname = 'public' and tablename = 'document_items' and policyname = 'document_items_select_anon'
  ) then
    create policy document_items_select_anon on public.document_items for select to anon using (true);
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1 from pg_policies where schemaname = 'public' and tablename = 'document_items' and policyname = 'document_items_insert_anon'
  ) then
    create policy document_items_insert_anon on public.document_items for insert to anon with check (true);
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1 from pg_policies where schemaname = 'public' and tablename = 'document_items' and policyname = 'document_items_update_anon'
  ) then
    create policy document_items_update_anon on public.document_items for update to anon using (true) with check (true);
  end if;
end
$$;
