export type SharedPreviewItem = {
  productId: string | null;
  seq: number;
  name1: string;
  name2: string;
  gubun: string;
  qty: number;
  unitPrice: number;
  supply: number;
  vat: boolean;
  orderDate: string | null;
  arriveDate: string | null;
  releaseNote: string;
  invoiceNote: string;
  eaPerB: number | null;
  boxPerP: number | null;
  pallet: number | null;
  box: number | null;
};

export type SharedPreviewData = {
  issueNo: string;
  clientId?: string | null;
  client: string;
  manager: string;
  managerTel: string;
  receiver: string;
  supplierBizNo: string;
  supplierName: string;
  supplierOwner: string;
  supplierAddress: string;
  supplierBusinessType: string;
  supplierBusinessItem: string;
  orderDate: string | null;
  arriveDate: string | null;
  deliveryAddr: string;
  remark: string;
  requestNote: string;
  totalSupply: number;
  totalVat: number;
  totalAmount: number;
  items: SharedPreviewItem[];
};
