export type DocumentStatus = 'ST00' | 'ST01';

export type DocumentItemPayload = {
  seq: number;
  name1: string;
  name2: string;
  gubun: string;
  qty: number;
  unitPrice: number;
  supply: number;
  vat: boolean;
  orderDate: string | null;
  arriveDate: string | null;
  itemNote: string;
  eaPerB: number | null;
  boxPerP: number | null;
  customPallet: number | null;
  customBox: number | null;
};

export type DocumentPayload = {
  issueNo: string;
  client: string;
  manager: string;
  managerTel: string;
  receiver: string;
  supplierBizNo: string;
  supplierName: string;
  supplierOwner: string;
  supplierAddress: string;
  supplierBusinessType: string;
  supplierBusinessItem: string;
  orderDate: string | null;
  arriveDate: string | null;
  deliveryAddr: string;
  remark: string;
  requestNote: string;
  totalSupply: number;
  totalVat: number;
  totalAmount: number;
  author: string;
  status: DocumentStatus;
  items: DocumentItemPayload[];
};

export type DocumentHistoryItem = {
  id: string;
  seq: number;
  name1: string;
  name2: string;
  gubun: string;
  qty: number;
  unitPrice: number;
  supply: number;
  vat: boolean;
  orderDate: string | null;
  arriveDate: string | null;
  itemNote: string;
  eaPerB: number | null;
  boxPerP: number | null;
  customPallet: number | null;
  customBox: number | null;
  delYn: 'Y' | 'N';
  updatedAt: string | null;
  updatedBy: string;
};

export type DocumentHistory = {
  id: string;
  issueNo: string;
  client: string;
  manager: string;
  managerTel: string;
  receiver: string;
  supplierBizNo: string;
  supplierName: string;
  supplierOwner: string;
  supplierAddress: string;
  supplierBusinessType: string;
  supplierBusinessItem: string;
  orderDate: string | null;
  arriveDate: string | null;
  deliveryAddr: string;
  remark: string;
  requestNote: string;
  totalSupply: number;
  totalVat: number;
  totalAmount: number;
  author: string;
  status: DocumentStatus;
  createdAt: string | null;
  updatedAt: string | null;
  updatedBy: string;
  delYn: 'Y' | 'N';
  items: DocumentHistoryItem[];
};
